export const FETCH_USER = 'FETCH_USER';
export const FETCH_USER_REJECTED = 'FETCH_USER_REJECTED';
export const FETCH_USER_FULFILLED = 'FETCH_USER_FULFILLED';

export const FETCH_USERS = 'FETCH_USERS';
export const FETCH_USERS_REJECTED = 'FETCH_USERS_REJECTED';
export const FETCH_USERS_FULFILLED = 'FETCH_USERS_FULFILLED';

export const FETCH_USER_PAYMENTS = 'FETCH_USER_PAYMENTS';
export const FETCH_USER_PAYMENTS_REJECTED = 'FETCH_USER_PAYMENTS_REJECTED';
export const FETCH_USER_PAYMENTS_FULFILLED = 'FETCH_USER_PAYMENTS_FULFILLED';

export const MAKE_PAYMENT = 'MAKE_PAYMENT';
export const MAKE_PAYMENT_REJECTED = 'MAKE_PAYMENT_REJECTED';
export const MAKE_PAYMENT_FULFILLED = 'MAKE_PAYMENT_FULFILLED';

export const MAKE_TRANSACTION = 'MAKE_PAYMENT';
export const MAKE_TRANSACTION_REJECTED = 'MAKE_PAYMENT_REJECTED';
export const MAKE_TRANSACTION_FULFILLED = 'MAKE_PAYMENT_FULFILLED';

export const MAKE_PAST_DUE_PAYMENT = 'MAKE_PAST_DUE_PAYMENT';
export const MAKE_PAST_DUE_PAYMENT_REJECTED = 'MAKE_PAST_DUE_PAYMENT_REJECTED';
export const MAKE_PAST_DUE_PAYMENT_FULFILLED = 'MAKE_PAST_DUE_PAYMENT_FULFILLED';

export const REMOVE_USER = 'REMOVE_USER';
export const REMOVE_USER_REJECTED = 'REMOVE_USER_REJECTED';
export const REMOVE_USER_FULFILLED = 'REMOVE_USER_FULFILLED';

export const UPDATE_USER = 'UPDATE_USER';
export const UPDATE_USER_REJECTED = 'UPDATE_USER_REJECTED';
export const UPDATE_USER_FULFILLED = 'UPDATE_USER_FULFILLED';

export const LOGIN = 'LOGIN';
export const LOGIN_REJECTED = 'LOGIN_REJECTED';
export const LOGIN_FULFILLED = 'LOGIN_FULFILLED';

export const ADD_USER = 'ADD_USER';
export const ADD_USER_REJECTED = 'ADD_USER_REJECTED';
export const ADD_USER_FULFILLED = 'ADD_USER_FULFILLED';

export const FETCH_ACCOUNTS = 'FETCH_ACCOUNTS';
export const FETCH_ACCOUNTS_REJECTED = 'FETCH_ACCOUNTS_REJECTED';
export const FETCH_ACCOUNTS_FULFILLED = 'FETCH_ACCOUNTS_FULFILLED';

export const FETCH_ALL_TRANSACTIONS = 'FETCH_ALL_TRANSACTIONS';
export const FETCH_ALL_TRANSACTIONS_REJECTED = 'FETCH_ALL_TRANSACTIONS_REJECTED';
export const FETCH_ALL_TRANSACTIONS_FULFILLED = 'FETCH_ALL_TRANSACTIONS_FULFILLED';


export const SET_ACTIVE_USER = 'SET_ACTIVE_USER';
export const SET_EDITING_MODE = 'SET_EDITING_MODE';
export const CLEAR_EDITING_MODE = 'CLEAR_EDITING_MODE';
export const SET_ACTIVE_TRANSACTION = 'SET_ACTIVE_TRANSACTION';

export const LOGOUT = 'LOGOUT';
