const FETCH_USER = 'FETCH_USER';
const FETCH_USER_REJECTED = 'FETCH_USER_REJECTED';
const FETCH_USER_FULFILLED = 'FETCH_USER_FULFILLED';

const FETCH_USERS = 'FETCH_USERS';
const FETCH_USERS_REJECTED = 'FETCH_USERS_REJECTED';
const FETCH_USERS_FULFILLED = 'FETCH_USERS_FULFILLED';

const FETCH_USER_PAYMENTS = 'FETCH_USER_PAYMENTS';
const FETCH_USER_PAYMENTS_REJECTED = 'FETCH_USER_PAYMENTS_REJECTED';
const FETCH_USER_PAYMENTS_FULFILLED = 'FETCH_USER_PAYMENTS_FULFILLED';

const MAKE_PAYMENT = 'MAKE_PAYMENT';
const MAKE_PAYMENT_REJECTED = 'MAKE_PAYMENT_REJECTED';
const MAKE_PAYMENT_FULFILLED = 'MAKE_PAYMENT_FULFILLED';

const MAKE_PAST_DUE_PAYMENT = 'MAKE_PAST_DUE_PAYMENT';
const MAKE_PAST_DUE_PAYMENT_REJECTED = 'MAKE_PAST_DUE_PAYMENT_REJECTED';
const MAKE_PAST_DUE_PAYMENT_FULFILLED = 'MAKE_PAST_DUE_PAYMENT_FULFILLED';

const REMOVE_USER = 'REMOVE_USER';
const REMOVE_USER_REJECTED = 'REMOVE_USER_REJECTED';
const REMOVE_USER_FULFILLED = 'REMOVE_USER_FULFILLED';

const UPDATE_USER = 'UPDATE_USER';
const UPDATE_USER_REJECTED = 'UPDATE_USER_REJECTED';
const UPDATE_USER_FULFILLED = 'UPDATE_USER_FULFILLED';

const LOGIN = 'LOGIN';
const LOGIN_REJECTED = 'LOGIN_REJECTED';
const LOGIN_FULFILLED = 'LOGIN_FULFILLED';

const SIGN_UP = 'SIGN_UP';
const SIGN_UP_REJECTED = 'SIGN_UP_REJECTED';
const SIGN_UP_FULFILLED = 'SIGN_UP_FULFILLED';

const FETCH_ACCOUNTS = 'FETCH_ACCOUNTS';
const FETCH_ACCOUNTS_REJECTED = 'FETCH_ACCOUNTS_REJECTED';
const FETCH_ACCOUNTS_FULFILLED = 'FETCH_ACCOUNTS_FULFILLED';

const FETCH_ALL_PAYMENTS = 'FETCH_ALL_PAYMENTS';
const FETCH_ALL_PAYMENTS_REJECTED = 'FETCH_ALL_PAYMENTS_REJECTED';
const FETCH_ALL_PAYMENTS_FUFILLED = 'FETCH_ALL_PAYMENTS_FUFILLED';


const LOGOUT = 'LOGOUT';
